server:
  port: 8000

spring:
  application:
    name: gulimall-member
  datasource:
    username: root
    password: 204317
    url: jdbc:mysql://localhost:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

